services:
  es:
    image: ikeshun15/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - http.port=9200
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:${ELASTICSEARCH_PORT}
      I18N_LOCALE: ja-JP
    depends_on:
      - es
